# Use the official MongoDB image
FROM mongo:latest

# Set the MongoDB environment variables
ENV MONGO_INITDB_ROOT_USERNAME=admin
ENV MONGO_INITDB_ROOT_PASSWORD=password
ENV MONGO_INITDB_DATABASE=userDB

# Copy the setup script to the container
COPY setup.js /docker-entrypoint-initdb.d/

# Expose the default MongoDB port
EXPOSE 27017
